### ISSUE TITLE
says mbuu is an invalid stock 

### ISSUE THREAD

**Issue by serhunya** [mrhappyasthma/IsThisStockGood#52] opened 2022-06-29 20:09 UTC
thank you for your great work

**Comment by mrhappyasthma** [comment] 2022-06-30 06:09
it's crashing. i think due to how i quickly parsed the new data source. ill see if i can figure it out

**Comment by mrhappyasthma** [comment] 2022-06-30 06:27
Fixed in https://github.com/mrhappyasthma/IsThisStockGood/commit/a5709debc0be58dfc2ecf117644e512e100b5577

Also this stock looking pretty good from the numbers. Nice find.

**Closed as completed by mrhappyasthma** 2022-06-30 06:27 UTC

**Comment by mrhappyasthma** [comment] 2022-06-30 06:30
New build is deployed. Confirmed that `mbuu` is working on the main webpage.

**Comment by serhunya** [comment] 2022-06-30 13:28
Thank you for fixing it!
